FROM nginx:alpine
#COPY . /usr/share/nginx/html

RUN apk add git 
RUN mkdir /nginx_php

RUN chmod -R 0777 /nginx_php/


RUN apk --no-cache add \
        php7 \
        php7-ctype \
        php7-curl \
        php7-dom \
        php7-fileinfo \
        php7-ftp \
        php7-iconv \
        php7-json \
        php7-mbstring \
        php7-mysqlnd \
        php7-openssl \
        php7-pdo \
        php7-pdo_sqlite \
        php7-pear \
        php7-phar \
        php7-posix \
        php7-session \
        php7-simplexml \
        php7-sqlite3 \
        php7-tokenizer \
        php7-xml \
        php7-xmlreader \
        php7-xmlwriter \
        php7-zlib \ 
        php7-mysqli \
	php7-pdo_mysql \
        php7-zip \
        php7-exif
#RUN cd /tmp && git clone https://github.com/systemd/systemd

#RUN echo "unicode=\"YES\"" >> /etc/rc.conf && \
 #   apk add --no-cache --virtual .build_deps \
  #      autoconf file g++ gcc libc-dev make pkgconf python3 ninja \
   #     util-linux pciutils usbutils coreutils binutils findutils grep \
  #      build-base gcc abuild binutils binutils-doc gcc-doc gperf libcap libcap-dev \
    #    valgrind-dev \
   # && \
#    pip3 install meson
RUN chown -R nginx:nginx /nginx_php/


COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

RUN apk add git

#RUN apk add bash

RUN apk add composer

RUN apk add supervisor

RUN apk search php7 | more

RUN apk add php7 php7-fpm php7-opcache

#RUN apk add php74

RUN apk add php7-gd php7-mysqli php7-zlib php7-curl php7-json

RUN apk  add php7-xmlwriter \
            php7-simplexml \
            php7-fileinfo \
            php7-tokenizer 

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer

#RUN apk add mysql mysql-client && \
#addgroup mysql mysql && \
#   mkdir run/mysqld && \
#    touch /var/run/mysqld/mysqld.sock && \
#    touch /var/run/mysqld/mysqld.pid && \
#    chown -R mysql:mysql /var/run/mysqld/mysqld.sock && \
#    chown -R mysql:mysql /var/run/mysqld/mysqld.pid && \
#    chmod -R 644 /var/run/mysqld/mysqld.sock
#COPY somedb2 /var/lib/
ARG CACHEBUST=1
COPY git-grad .
RUN git config --global http.sslVerify false
RUN git config --global credential.helper 'store --file git-grad'
#RUN git clone http://192.168.1.250/root/alpine-laravel-sample.git  /nginx_php/
#RUN git clone http://192.168.1.250/root/industry-website.git /nginx_php/
#RUN apk add mysql mysql-client
#RUN git clone https://admin@example.com:FRZfrs9297@82.137.226.40:44357/tit/laravel-backend-boilerplate
#RUN composer install -d /nginx_php/ && php  /nginx_php/artisan key:generate
#RUN git clone http://192.168.1.250/education/education-dashboard.git /nginx_php/
#COPY connmysqlioo.php /nginx_php/public/
RUN ping 192.168.1.250 -c 4
#RUN git config --global credential.helper 'store --file git-grad' && git clone  http://root:FRZfrs9297@192.168.1.250/root/education.git /nginx_php/
#RUN apk add openrc
COPY connmysqlioo.php /nginx_php/public/index.php
RUN chmod -R 0777 /nginx_php/

COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

COPY conf/nginx2.conf /etc/nginx/conf.d/sbe.conf

COPY conf/nginx-selfsigned.crt /server.crt
COPY conf/nginx-selfsigned.key /server.key
 
COPY supervisord_alpine.conf /etc/supervisord.conf

CMD ["supervisord", "-n"]

